companies = [
  {
    "id": 1,
    "biz_name": "Harding's Towing II",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "90 Centre Dr",
    "e_city": "Rochester",
    "e_state": "NY",
    "e_postal": 14623,
    "e_zip_full": "14623-2302",
    "e_country": "USA",
    "loc_county": "Monroe",
    "loc_area_code": 585,
    "loc_FIPS": 36055,
    "loc_MSA": 6840,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 43.0873,
    "loc_LAT_poly": 43.096005,
    "loc_LONG_centroid": -77.6328,
    "loc_LONG_poly": -77.633981,
    "biz_phone": "(585) 424-3200",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": "http://www.uneedatow.com",
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 2,
    "biz_name": "24 Hour Towing & Repair",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "400 E 85th St",
    "e_city": "New York",
    "e_state": "NY",
    "e_postal": 10028,
    "e_zip_full": "10028-6385",
    "e_country": "USA",
    "loc_county": "New York",
    "loc_area_code": 212,
    "loc_FIPS": 36061,
    "loc_MSA": 0,
    "loc_PMSA": 5600,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 40.7764,
    "loc_LAT_poly": 40.77598,
    "loc_LONG_centroid": -73.9527,
    "loc_LONG_poly": -73.949721,
    "biz_phone": "(212) 595-2831",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 3,
    "biz_name": "24hr TOWING INC",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "547 W 49th St",
    "e_city": "New York",
    "e_state": "NY",
    "e_postal": 10019,
    "e_zip_full": "10019-7142",
    "e_country": "USA",
    "loc_county": "New York",
    "loc_area_code": 212,
    "loc_FIPS": 36061,
    "loc_MSA": 0,
    "loc_PMSA": 5600,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 40.7652,
    "loc_LAT_poly": 40.764769,
    "loc_LONG_centroid": -73.9853,
    "loc_LONG_poly": -73.993575,
    "biz_phone": "(718) 617-3030",
    "biz_phone_ext": 0,
    "biz_fax": "(718) 328-0952",
    "biz_email": 0,
    "web_url": "http://www.springtechcorp.com/",
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 4,
    "biz_name": "89 Service Center",
    "biz_info": "89 Service Center in Mount Airy, NC is a private company categorized under Automobile Inspection Stations. Current estimates show this company has an annual revenue of less than $500,000 and employs a staff of approximately 1 to 4. Companies like 89 Service Center usually offer: Auto Electrical Systems, Electrical System In A Car, Electrical System Of A Car, Vehicle Electrical Systems and Electrical Systems In Cars.",
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "4216 Nc 89 Hwy E",
    "e_city": "Walnut Cove",
    "e_state": "NC",
    "e_postal": 27052,
    "e_zip_full": "27052-7654",
    "e_country": "USA",
    "loc_county": "Stokes",
    "loc_area_code": 336,
    "loc_FIPS": 37169,
    "loc_MSA": 3120,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 36.3289,
    "loc_LAT_poly": 36.338136,
    "loc_LONG_centroid": -80.1453,
    "loc_LONG_poly": -80.151532,
    "biz_phone": "(336) 591-4709",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 5,
    "biz_name": "A & A Towing & Repair",
    "biz_info": "Trust A & A Towing & Repair with all your towing and auto repair needs. We are now serving the Greater Orlando areas of Florida",
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "8112 E Colonial Dr",
    "e_city": "Orlando",
    "e_state": "FL",
    "e_postal": 32817,
    "e_zip_full": "32817-3906",
    "e_country": "USA",
    "loc_county": "Orange",
    "loc_area_code": 407,
    "loc_FIPS": 12095,
    "loc_MSA": 5960,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 28.5912,
    "loc_LAT_poly": 28.568167,
    "loc_LONG_centroid": -81.2456,
    "loc_LONG_poly": -81.27746,
    "biz_phone": "(407) 275-9808",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": "http://www.aatowingorlando.com/",
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 6,
    "biz_name": "A & A Towing-Flatbed & Lockout Service",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "13024 Halldale Ave",
    "e_city": "Gardena",
    "e_state": "CA",
    "e_postal": 90249,
    "e_zip_full": "90249-2118",
    "e_country": "USA",
    "loc_county": "Los Angeles",
    "loc_area_code": 310,
    "loc_FIPS": 6037,
    "loc_MSA": 0,
    "loc_PMSA": 4480,
    "loc_TZ": "PST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 33.9005,
    "loc_LAT_poly": 33.914141,
    "loc_LONG_centroid": -118.3177,
    "loc_LONG_poly": -118.302179,
    "biz_phone": "(310) 516-0396",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 7,
    "biz_name": "A & R Trailers",
    "biz_info": "We understand why our customers select us for all of their towing and carrying needs. We have a proven track record of performing quality work at a competitive price. We will make sure we walk you through the process, so you feel comfortable that you made the right decision and that we provided the safest solution solution.",
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "5580 Cheviot Rd",
    "e_city": "Cincinnati",
    "e_state": "OH",
    "e_postal": 45247,
    "e_zip_full": "45247-7094",
    "e_country": "USA",
    "loc_county": "Hamilton",
    "loc_area_code": 513,
    "loc_FIPS": 39061,
    "loc_MSA": 0,
    "loc_PMSA": 1640,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 39.2201,
    "loc_LAT_poly": 39.192674,
    "loc_LONG_centroid": -84.6531,
    "loc_LONG_poly": -84.598939,
    "biz_phone": "(513) 385-0722",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": "http://www.artrailer.com",
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 8,
    "biz_name": "A & Sons Towing",
    "biz_info": "Since 1997, Al & Son's Towing Inc. has been a family owned and operated towing company serving the Los Angeles, San Bernardino and Orange County areas.",
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "2901 S Riverside Ave, Lot E",
    "e_city": "Colton",
    "e_state": "CA",
    "e_postal": 92324,
    "e_zip_full": 0,
    "e_country": "USA",
    "loc_county": "San Bernardino",
    "loc_area_code": 909,
    "loc_FIPS": 6071,
    "loc_MSA": 0,
    "loc_PMSA": 6780,
    "loc_TZ": "PST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 34.0027,
    "loc_LAT_poly": 34.021524,
    "loc_LONG_centroid": -117.2405,
    "loc_LONG_poly": -117.362614,
    "biz_phone": "(951) 276-8090",
    "biz_phone_ext": 0,
    "biz_fax": "(909) 276-2470",
    "biz_email": "aandsonstowing@privaten.net",
    "web_url": "http://alnsonstowing.com/",
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 9,
    "biz_name": "A & T Towing",
    "biz_info": "Our goal is to provide you with great service and high-quality workmanship at a fair price. Please browse our website to learn more about us and our commitment to the best in automotive service.",
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "821 N 21st St",
    "e_city": "East St Louis",
    "e_state": "IL",
    "e_postal": 62205,
    "e_zip_full": "62205-2701",
    "e_country": "USA",
    "loc_county": "Saint Clair",
    "loc_area_code": 618,
    "loc_FIPS": 17163,
    "loc_MSA": 7040,
    "loc_PMSA": 0,
    "loc_TZ": "CST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 38.6057,
    "loc_LAT_poly": 38.621649,
    "loc_LONG_centroid": -90.1182,
    "loc_LONG_poly": -90.12952,
    "biz_phone": "(618) 274-8639",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": "http://www.procarcarezone.com/shops/a__t_towing_and_service_center.com",
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 10,
    "biz_name": "A 1 Towing",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "6633 Roosevelt Dr",
    "e_city": "Ketchikan",
    "e_state": "AK",
    "e_postal": 99901,
    "e_zip_full": "99901-9732",
    "e_country": "USA",
    "loc_county": "Ketchikan Gateway",
    "loc_area_code": 907,
    "loc_FIPS": 2130,
    "loc_MSA": 0,
    "loc_PMSA": 0,
    "loc_TZ": "PST-1",
    "loc_DST": "Y",
    "loc_LAT_centroid": 55.5909,
    "loc_LAT_poly": 55.306546,
    "loc_LONG_centroid": -131.3492,
    "loc_LONG_poly": -131.52957,
    "biz_phone": "(907) 247-6633",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 11,
    "biz_name": "A 2 Z Towing",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "45101 Commerce St",
    "e_city": "Indio",
    "e_state": "CA",
    "e_postal": 92201,
    "e_zip_full": "92201-3439",
    "e_country": "USA",
    "loc_county": "Riverside",
    "loc_area_code": 760,
    "loc_FIPS": 6065,
    "loc_MSA": 0,
    "loc_PMSA": 6780,
    "loc_TZ": "PST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 33.7269,
    "loc_LAT_poly": 33.72215,
    "loc_LONG_centroid": -116.2361,
    "loc_LONG_poly": -116.203439,
    "biz_phone": "(760) 342-3518",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": "a2ztow@aol.com",
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 12,
    "biz_name": "A A Dot Towing",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "8130 Monroe Ave",
    "e_city": "Stanton",
    "e_state": "CA",
    "e_postal": 90680,
    "e_zip_full": "90680-2645",
    "e_country": "USA",
    "loc_county": "Orange",
    "loc_area_code": 714,
    "loc_FIPS": 6059,
    "loc_MSA": 0,
    "loc_PMSA": 5945,
    "loc_TZ": "PST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 33.8022,
    "loc_LAT_poly": 33.805468,
    "loc_LONG_centroid": -117.9951,
    "loc_LONG_poly": -117.989976,
    "biz_phone": "(714) 527-6408",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": "aadottowing@aol.com",
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 14,
    "biz_name": "A Aamirsen Towing",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "6333 Mount Ada Rd",
    "e_city": "San Diego",
    "e_state": "CA",
    "e_postal": 92111,
    "e_zip_full": "92111-3121",
    "e_country": "USA",
    "loc_county": "San Diego",
    "loc_area_code": 858,
    "loc_FIPS": 6073,
    "loc_MSA": 7320,
    "loc_PMSA": 0,
    "loc_TZ": "PST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 32.8068,
    "loc_LAT_poly": 32.81919,
    "loc_LONG_centroid": -117.1685,
    "loc_LONG_poly": -117.174734,
    "biz_phone": "(858) 505-9096",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 15,
    "biz_name": "A Best Towing",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "3200 Griffin Rd",
    "e_city": "Hollywood",
    "e_state": "FL",
    "e_postal": 33312,
    "e_zip_full": 0,
    "e_country": "USA",
    "loc_county": "Broward",
    "loc_area_code": 954,
    "loc_FIPS": 12011,
    "loc_MSA": 0,
    "loc_PMSA": 2680,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 26.0861,
    "loc_LAT_poly": 26.062181,
    "loc_LONG_centroid": -80.1822,
    "loc_LONG_poly": -80.185692,
    "biz_phone": "(954) 989-9090",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 16,
    "biz_name": "A Charlie's Towing Service Inc",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "6171 Van Nuys Blvd",
    "e_city": "Van Nuys",
    "e_state": "CA",
    "e_postal": 91401,
    "e_zip_full": "91401-3307",
    "e_country": "USA",
    "loc_county": "Los Angeles",
    "loc_area_code": 818,
    "loc_FIPS": 6037,
    "loc_MSA": 0,
    "loc_PMSA": 4480,
    "loc_TZ": "PST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 34.1781,
    "loc_LAT_poly": 34.182075,
    "loc_LONG_centroid": -118.4316,
    "loc_LONG_poly": -118.448896,
    "biz_phone": "(818) 901-0602",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 17,
    "biz_name": "A Plus Towing & Automotive",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "495 Valenti Ct",
    "e_city": "Riverdale",
    "e_state": "GA",
    "e_postal": 30274,
    "e_zip_full": "30274-4226",
    "e_country": "USA",
    "loc_county": "Clayton",
    "loc_area_code": 770,
    "loc_FIPS": 13063,
    "loc_MSA": 520,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 33.5562,
    "loc_LAT_poly": 33.52863,
    "loc_LONG_centroid": -84.3998,
    "loc_LONG_poly": -84.406528,
    "biz_phone": "(404) 624-4708",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 18,
    "biz_name": "A Pro Tow",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "5711 West Fligh Avenue",
    "e_city": "Tampa",
    "e_state": "FL",
    "e_postal": 33602,
    "e_zip_full": 0,
    "e_country": "USA",
    "loc_county": "Hillsborough",
    "loc_area_code": 813,
    "loc_FIPS": 12057,
    "loc_MSA": 8280,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 27.9575,
    "loc_LAT_poly": 0,
    "loc_LONG_centroid": -82.4576,
    "loc_LONG_poly": 0,
    "biz_phone": "(813) 269-7174",
    "biz_phone_ext": 0,
    "biz_fax": "(813) 269-7174",
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 19,
    "biz_name": "A Reliable Towing & Recovery- Inc.",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "9426 66th St N",
    "e_city": "Pinellas Park",
    "e_state": "FL",
    "e_postal": 33782,
    "e_zip_full": "33782-3001",
    "e_country": "USA",
    "loc_county": "Pinellas",
    "loc_area_code": 727,
    "loc_FIPS": 12103,
    "loc_MSA": 8280,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 27.8607,
    "loc_LAT_poly": 27.857732,
    "loc_LONG_centroid": -82.7135,
    "loc_LONG_poly": -82.729033,
    "biz_phone": "(727) 545-8697",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": "general@reliabletowing.com",
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 20,
    "biz_name": "A S C O Inc",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "1684 E National Pike",
    "e_city": "Scenery Hill",
    "e_state": "PA",
    "e_postal": 15360,
    "e_zip_full": "15360-1019",
    "e_country": "USA",
    "loc_county": "Washington",
    "loc_area_code": 724,
    "loc_FIPS": 42125,
    "loc_MSA": 6280,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 40.0969,
    "loc_LAT_poly": 40.10525,
    "loc_LONG_centroid": -80.0956,
    "loc_LONG_poly": -80.105177,
    "biz_phone": "(724) 945-5525",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 21,
    "biz_name": "A Superior Wrecker Sales",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "3160 Birmingham Hwy",
    "e_city": "Montgomery",
    "e_state": "AL",
    "e_postal": 36108,
    "e_zip_full": "36108-1714",
    "e_country": "USA",
    "loc_county": "Montgomery",
    "loc_area_code": 334,
    "loc_FIPS": 1101,
    "loc_MSA": 5240,
    "loc_PMSA": 0,
    "loc_TZ": "CST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 32.3488,
    "loc_LAT_poly": 32.370237,
    "loc_LONG_centroid": -86.4016,
    "loc_LONG_poly": -86.374267,
    "biz_phone": "(334) 269-1257",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 22,
    "biz_name": "A To Z Mustangs",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "181 Andover Rd",
    "e_city": "Fairless Hills",
    "e_state": "PA",
    "e_postal": 19030,
    "e_zip_full": "19030-2726",
    "e_country": "USA",
    "loc_county": "Bucks",
    "loc_area_code": 215,
    "loc_FIPS": 42017,
    "loc_MSA": 0,
    "loc_PMSA": 6160,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 40.1749,
    "loc_LAT_poly": 40.177262,
    "loc_LONG_centroid": -74.8541,
    "loc_LONG_poly": -74.866387,
    "biz_phone": "(215) 547-4699",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 23,
    "biz_name": "A Wrecker Service",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "201 Shelby St",
    "e_city": "Murfreesboro",
    "e_state": "TN",
    "e_postal": 37127,
    "e_zip_full": "37127-5504",
    "e_country": "USA",
    "loc_county": "Rutherford",
    "loc_area_code": 615,
    "loc_FIPS": 47149,
    "loc_MSA": 5360,
    "loc_PMSA": 0,
    "loc_TZ": "CST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 35.7571,
    "loc_LAT_poly": 35.815253,
    "loc_LONG_centroid": -86.3959,
    "loc_LONG_poly": -86.393807,
    "biz_phone": "(615) 217-7990",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 24,
    "biz_name": "A-1 Auto Service Center",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "3523 Reid St",
    "e_city": "Palatka",
    "e_state": "FL",
    "e_postal": 32177,
    "e_zip_full": "32177-2518",
    "e_country": "USA",
    "loc_county": "Putnam",
    "loc_area_code": 386,
    "loc_FIPS": 12107,
    "loc_MSA": 0,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 29.7389,
    "loc_LAT_poly": 29.657099,
    "loc_LONG_centroid": -81.6715,
    "loc_LONG_poly": -81.665561,
    "biz_phone": "(386) 328-5661",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 25,
    "biz_name": "A-1 Braden's Towing & Auto Repair",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "2501 Lincoln Ave",
    "e_city": "Wheeling",
    "e_state": "WV",
    "e_postal": 26003,
    "e_zip_full": "26003-5332",
    "e_country": "USA",
    "loc_county": "Ohio",
    "loc_area_code": 304,
    "loc_FIPS": 54069,
    "loc_MSA": 9000,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 40.0729,
    "loc_LAT_poly": 40.04783,
    "loc_LONG_centroid": -80.6524,
    "loc_LONG_poly": -80.648549,
    "biz_phone": "(304) 243-1586",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 26,
    "biz_name": "A-1 Rodriguez Tire & Auto Service",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "4157 North Rd",
    "e_city": "Orangeburg",
    "e_state": "SC",
    "e_postal": 29118,
    "e_zip_full": "29118-1129",
    "e_country": "USA",
    "loc_county": "Orangeburg",
    "loc_area_code": 803,
    "loc_FIPS": 45075,
    "loc_MSA": 0,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 33.5398,
    "loc_LAT_poly": 33.546762,
    "loc_LONG_centroid": -80.8866,
    "loc_LONG_poly": -80.916614,
    "biz_phone": "(803) 534-4149",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 27,
    "biz_name": "A-1 Sav-On Rentals",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "3712 Main St",
    "e_city": "Chula Vista",
    "e_state": "CA",
    "e_postal": 91911,
    "e_zip_full": "91911-5835",
    "e_country": "USA",
    "loc_county": "San Diego",
    "loc_area_code": 619,
    "loc_FIPS": 6073,
    "loc_MSA": 7320,
    "loc_PMSA": 0,
    "loc_TZ": "PST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 32.6069,
    "loc_LAT_poly": 32.594853,
    "loc_LONG_centroid": -117.0565,
    "loc_LONG_poly": -117.053257,
    "biz_phone": "(619) 425-2040",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": "http://www.a1savon.com",
    "web_meta_title": "Chula Vista Self Storage Units & San Diego Rental Company",
    "web_meta_desc": "San-On Storage is a leading Self Storage and Rental Company in Chula Vista, San Diego. We have the best Self Storage Units to meet your requirements.",
    "web_meta_keys": "Chula Vista Storage, Chula Vista Storage Company, Chula Vista Self Storage Units, Chula Vista Self Storage Rental, San Diego Self Storage Rental, San Diego Self Storage Units"
  },
  {
    "id": 28,
    "biz_name": "A-2-Z International 1 A-R-Hi",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "Po Box 432",
    "e_city": "Arcadia",
    "e_state": "CA",
    "e_postal": 91006,
    "e_zip_full": 0,
    "e_country": "USA",
    "loc_county": "Los Angeles",
    "loc_area_code": 626,
    "loc_FIPS": 6037,
    "loc_MSA": 0,
    "loc_PMSA": 4480,
    "loc_TZ": "PST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 34.138,
    "loc_LAT_poly": 34.1172361,
    "loc_LONG_centroid": -118.0283,
    "loc_LONG_poly": -118.0244639,
    "biz_phone": "(626) 449-6672",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 29,
    "biz_name": "A-A Now Towing",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "380 W 26th St",
    "e_city": "New York",
    "e_state": "NY",
    "e_postal": 10001,
    "e_zip_full": "10001-5813",
    "e_country": "USA",
    "loc_county": "New York",
    "loc_area_code": 212,
    "loc_FIPS": 36061,
    "loc_MSA": 0,
    "loc_PMSA": 5600,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 40.75,
    "loc_LAT_poly": 40.748081,
    "loc_LONG_centroid": -73.9967,
    "loc_LONG_poly": -73.999509,
    "biz_phone": "(646) 862-5220",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 31,
    "biz_name": "Aa-Greg'S Towing",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "239 Juan Tabo Blvd NE",
    "e_city": "Albuquerque",
    "e_state": "NM",
    "e_postal": 87123,
    "e_zip_full": "87123-3042",
    "e_country": "USA",
    "loc_county": "Bernalillo",
    "loc_area_code": 505,
    "loc_FIPS": 35001,
    "loc_MSA": 200,
    "loc_PMSA": 0,
    "loc_TZ": "MST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 35.0653,
    "loc_LAT_poly": 35.072366,
    "loc_LONG_centroid": -106.4737,
    "loc_LONG_poly": -106.515423,
    "biz_phone": "(505) 271-1300",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  },
  {
    "id": 32,
    "biz_name": "Aaa-Francis Service",
    "biz_info": 0,
    "cat_primary": "Towing",
    "cat_sub": "Auto Towing Equipment",
    "e_address": "11923 Us-23 S",
    "e_city": "Ossineke",
    "e_state": "MI",
    "e_postal": 49766,
    "e_zip_full": "49766-9507",
    "e_country": "USA",
    "loc_county": "Alpena",
    "loc_area_code": 989,
    "loc_FIPS": 26007,
    "loc_MSA": 0,
    "loc_PMSA": 0,
    "loc_TZ": "EST",
    "loc_DST": "Y",
    "loc_LAT_centroid": 44.9058,
    "loc_LAT_poly": 44.903385,
    "loc_LONG_centroid": -83.4572,
    "loc_LONG_poly": -83.442841,
    "biz_phone": "(989) 471-2356",
    "biz_phone_ext": 0,
    "biz_fax": 0,
    "biz_email": 0,
    "web_url": 0,
    "web_meta_title": 0,
    "web_meta_desc": 0,
    "web_meta_keys": 0
  }
]


const request = require('request');

function getClosestTowCompany(locationCoordinates){
  var minDist = 1000;
  var closest, dist;
  var output = '';

  for (var index in companies){
    var company = companies[index];
    dist = Math.sqrt( Math.pow(locationCoordinates[0] - company["loc_LAT_centroid"], 2) + Math.pow(locationCoordinates[1] - company["loc_LONG_centroid"], 2));
    if (dist < minDist){
      minDist = dist;
      closest = index;
    }
    
  }
  output = companies[closest]['biz_name'] + '\n' + companies[closest]['biz_phone'] + '\n'
    + companies[closest]['e_address'] + ', ' + companies[closest]['e_city'] + ', ' + companies[closest]['e_state'];
  console.log(output)
  
}

function printCoordinates(coordinates) {
  console.log(coordinates);
}


function getCoordinates(cityName, callback) {
  request(
    `http://maps.google.com/maps/api/geocode/json?address=${cityName}`,
    function(error, response, body) {
      if (!error && response.statusCode === 200) {
        body = JSON.parse(response.body);
        coordinates = [body['results'][0]['geometry']['location']['lat'],body['results'][0]['geometry']['location']['lng']];
        //console.log(coordinates);
        callback(coordinates);
      }
    }
  );
};

var cityName = 'lincoln nebraska'
getCoordinates(cityName, printCoordinates);
// getCoordinates(cityName, getClosestTowCompany);






